# Colors (Dracula)
[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xffffff"
yellow = "0xf1fa8c"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x0b0e14"
foreground = "0xe6f2eb"

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[font]
size = 10

# https://www.nerdfonts.com/font-downloads  -- скачиваем отсюда шрифт и вставляет в терминал после чего вместе со шрифтом будут отоброжатся иконки файлов папок итд в том-же nvim
[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 9
y = 9

# initialization powershell version 7
[terminal.shell]
program = "pwsh"
